name: Suggest a Link
description: Suggest a new link to be added to the awesome list
title: "[LINK NAME]: "
labels: ["link"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a link! If this issue gets at least **5 likes (👍)**, the link will be automatically added to the README.
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this belong to?
      multiple: false
      options:
        - "API"
        - "Algorithms And Data Structures"
        - "Application Frameworks"
        - "Application Templates"
        - "Artificial Intelligence"
        - "Assembly Manipulation"
        - "Assets"
        - "Auth"
        - "Authentication And Authorization"
        - "Background Processing"
        - "Big Data"
        - "Blazor"
        - "Blockchain"
        - "Build Automation"
        - "Business Intelligence"
        - "CLI"
        - "CMS"
        - "Caching"
        - "Calendar"
        - "Cloud Storage"
        - "Code Analysis And Metrics"
        - "Code Snippets"
        - "Compilers, Transpilers And Languages"
        - "Compression"
        - "Configuration"
        - "Continuous Integration"
        - "Cryptography"
        - "Data Formats"
        - "Data Generators"
        - "Database Drivers"
        - "Database"
        - "Databases"
        - "Datetime"
        - "Decompilation"
        - "Deployment"
        - "Desktop"
        - "Directx"
        - "Distributed Computing"
        - "Distributed Systems"
        - "Documentation"
        - "E-commerce And Payments"
        - "ETL"
        - "Emulators"
        - "Environment Management"
        - "Event Aggregator And Messenger"
        - "Extensions"
        - "Feature Management"
        - "Functional Programming"
        - "GIS"
        - "GUI"
        - "Game Engines"
        - "Game"
        - "Git Tools"
        - "Graphics"
        - "Graphql"
        - "HTML And CSS"
        - "HTTP"
        - "IDE"
        - "Image Processing"
        - "Install Tools"
        - "Interactive Programming"
        - "Internationalization"
        - "Interoperability"
        - "Ioc"
        - "Javascript Engines"
        - "Libraries"
        - "Logging"
        - "MQTT"
        - "MVVM"
        - "Machine Learning And Data Science"
        - "Mail"
        - "Markdown Processors"
        - "Mathematics"
        - "Media"
        - "Metrics"
        - "Minification"
        - "Misc"
        - "Networking"
        - "ORM"
        - "Object To Object Mapping"
        - "Office"
        - "Other"
        - "PDF"
        - "Package Management"
        - "Parser Library"
        - "Profiler"
        - "Protocols"
        - "Query Builders"
        - "Queue"
        - "RPC"
        - "Reactive Programming"
        - "Real-time Communications"
        - "Runtimes"
        - "SDK And API Clients"
        - "SMS And Phone Calls"
        - "Scheduling"
        - "Search"
        - "Security"
        - "Serialization"
        - "Source Generator"
        - "Source Generators"
        - "State Machines"
        - "Static Site Generators"
        - "Strong Naming"
        - "Style Guide"
        - "Template Engine"
        - "Testing"
        - "Text Processing"
        - "Tools"
        - "Trading"
        - "UI Automation"
        - "UI"
        - "Unit Testing"
        - "Videos"
        - "Visual Studio Plugins"
        - "WPF"
        - "Web Browsers"
        - "Web Frameworks"
        - "Web Servers"
        - "Websocket"
        - "Windows Services"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: The URL to the resource
      placeholder: "https://github.com/..."
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: A brief description of what this resource does
      placeholder: "A popular high-performance JSON framework for .NET"
    validations:
      required: true
