name: Suggest a Link
description: Suggest a new link to be added to the awesome list
title: "...link title..."
labels: ["link"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a link! If this issue gets at least **5 likes (👍)**, the link will be automatically added to the README.
  - type: input
    id: category
    attributes:
      label: Category
      description: What category does this belong to?
      placeholder: "Libraries, Frameworks, Tools..."
    validations:
      required: true
  - type: input
    id: subcategory
    attributes:
      label: Subcategory
      description: What subcategory does this belong to? (Optional)
      placeholder: "Web, Mobile, Data Science..."
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: URL
      description: The URL to the resource
      placeholder: "https://github.com/..."
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: A brief description of what this resource does
      placeholder: "A popular high-performance JSON framework for .NET"
    validations:
      required: true
